Zhao
KingFarGrace/FindaService pull request #6
Opened 2023-05-03 21:25 UTC by ThomasJuan23

Finish("Register Page")

2023-05-04 10:37 UTC, KingFarGrace commented on frontend/src/pages/Reg/Reg.js
> +            { label:"Provider", value: "provider"}
value should be serviceProvider instead of provider

2023-05-04 10:45 UTC, KingFarGrace commented on frontend/src/api/index.js
> +                nickname,
username instead of nickname

2023-05-04 10:47 UTC, KingFarGrace requested changes
- For a service provider, it can be accepted to login only when they get approved by admin. There will be a return value from backend which is called "available", true means that the admin approved the account's registration.
- Also, the service provider need to provide more information than a customer.
- 2 more comments need to be noticed in file /Reg/Reg.js and /api/index.js

2023-05-04 10:48 UTC, KingFarGrace commented
为什么有两个pr，看起来是同一个分支

2023-05-05 00:10 UTC, ThomasJuan23 commented
> 为什么有两个pr，看起来是同一个分支
有一个错误的pull到master去了

2023-05-05 00:41 UTC, ThomasJuan23 commented
> * For a service provider, it can be accepted to login only when they get approved by admin. There will be a return value from backend which is called "available", true means that the admin approved the account's registration.
> * Also, the service provider need to provide more information than a customer.

1. 服务提供商需要提供的额外信息是我这边确定，还是你那边已经订好了
2. 前端需不需要做邮箱验证码的内容

2023-05-05 01:25 UTC, ThomasJuan23 commented
> * For a service provider, it can be accepted to login only when they get approved by admin. There will be a return value from backend which is called "available", true means that the admin approved the account's registration.

在服务提供商注册之后，如何让他们得知他们的注册通过了呢，可以通过邮件吗？我前段这边反馈给他们一个消息提醒叫他们等待确认邮件

2023-05-05 09:32 UTC, closed without merging